Feature/io2 136 register for vaccination
PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-backend pull request #15
Opened 2022-04-13 07:24 UTC by adambiel22

Dodane endpointy: 

GET /patient/vaccines
GET /patient/vaccination-slots
PUT /patient/vaccination-slots/{vaccinationSlotId}

Brak testów

2022-04-13 11:57 UTC, adamczykt requested changes

2022-04-13 11:57 UTC, adamczykt commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +            if (!VaccineEntity.Disease.isInEnum(disease)) {
Trochę dziwna nazwa imo (isInEnum). Nie zdradza za wystarczająco co robi. Nie lepiej coś w stylu isValidDiseaseName

2022-04-13 11:57 UTC, adamczykt commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +                                VaccineEntity.Disease.collectedLabels())));
Znów wydaje mi się, że collectedLabels() nie mowi co wlasciwie ta funkcja robi. getValidDiseaseNames?

2022-04-13 11:57 UTC, adamczykt commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +                return ResponseEntity.status(422).body(Map.of("success", false,
Generalnie z tego co widzę używaliśmy odpowiednich statusów z enuma HttpStatus, albo factory metod z Response Entity zamiast cyferek typu 422. Niezbyt ważne tho

2022-04-13 11:57 UTC, adamczykt commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +            return ResponseEntity.status(409).body(Map.of("success", false, "msg", e.getMessage()));
Tu też cyferki. Jak wyżej. Do uzgodnienia w teamie

2022-04-13 11:57 UTC, adamczykt commented on src/main/java/com/example/SOPSbackend/service/AdminService.java
> +        return doctorRepository.save(new DoctorEntity(doctor.getFirstName(), doctor.getLastName(), doctor.getEmail(), encoder.encode(doctor.getPassword())));
Ja bym już chyba rozbił return'a na dwie linijki co najmniej

2022-04-13 16:03 UTC, adambiel22 commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +                                VaccineEntity.Disease.collectedLabels())));
zmienione

2022-04-13 16:05 UTC, adambiel22 commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +                return ResponseEntity.status(422).body(Map.of("success", false,
Zmienione.

2022-04-13 16:07 UTC, adambiel22 commented on src/main/java/com/example/SOPSbackend/service/AdminService.java
> +        return doctorRepository.save(new DoctorEntity(doctor.getFirstName(), doctor.getLastName(), doctor.getEmail(), encoder.encode(doctor.getPassword())));
zmienione

2022-04-16 23:11 UTC, filipspych requested changes
To jest jeden z lepiej przemyślanych i napisanych kawałków kodu jakie czytałem. 

Wymaga wielu poprawek.

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/controller/AdminController.java
> +            return ResponseEntity.accepted().body(adminService.addDoctor(doctor));
To jest źle (zły response code), ale naprawiam to w swoim PR, więc tutaj zostawiamy.

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +        for (String disease : diseasesList) {
Można by (było by nowocześniej) też napisać np. tak, z użyciem leniwego obliczania streamów 
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/52869032/163692421-5efd76e4-0532-4eaf-ad80-5ebbee162bfd.png">

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +        } catch (AlreadyReservedException e) {
Można połączyć branche catch, żeby uniknąć powtarzania kodu.

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/controller/PatientController.java
> +        PatientEntity patient = (PatientEntity) authPrincipal.getUser();
Ta linijka i zmienna nie jest potrzebna. Wszyscy wiedzą co robi, to idiom. Może lepiej wyrzucić to do linijki 90, żeby nie tworzyć niepotrzebnych bytów?

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/dto/NewDoctorDto.java
> +    @NotNull String firstName, lastName, email, password;
Super, czyściutko 😍!

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/dto/VaccineIdDto.java
> +public class VaccineIdDto {
Ja bym nie przesadzał, zbyt dużo klas to z kolei zaciemnianie kodu. Można wczytać/wysłać bezpośrednio Long.

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/exception/AlreadyReservedException.java
> +    public AlreadyReservedException(String message) {
Super!

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/model/VaccinationEntity.java
> +    public enum Status {
Super!

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/model/VaccineEntity.java
> +            return BY_LABEL.keySet().stream().collect(Collectors.joining(","));
Biorąc pod uwagę użycie tej metody, dodałbym spację po przecinku.

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/model/VaccineEntity.java
> +                BY_LABEL.put(d.label, d);
bardzo fajnie użyty static 🤩 (chociaż darowałbym sobie te klamry i rozbicie na dwie linijki)

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/model/VaccineEntity.java
> +    public enum Disease {
Super! Bardzo fajny enum, bardzo fajne użycie właściwych Javie konstrukcji, 😱aż mnie zastanawia skąd to wszystko wiesz. Bardzo przemyślane. @adambiel22 

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/service/AdminService.java
> +    public DoctorEntity addDoctor(NewDoctorDto doctor) throws UserAlreadyExistException {
Jeszcze raz: super! (chodzi mi o użycie UAEE)

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/exception/AlreadyReservedException.java
> +    public AlreadyReservedException(String message) {
Niestety muszę dodać, że w takich sytuacjach rozszerzamy `Exception`, nie `Throwable`. Więcej informacji tutaj: https://docs.oracle.com/javase/specs/jls/se7/html/jls-11.html.
W Javie hierarchia wygląda jak niżej i właśnie dlatego deklarowanie czegoś co ma być sprawdzanym (checked) `Exception` jako `Throwable` jest mylące. Należy rozszerzać najbliższą naszemu zastosowaniu klasę z hierarchi `Throwable`. W tym wypadku rozszerzanie `Exception` jest raczej akceptowalne. @adambiel22 proszę zamknij ten wątek, gdy naprawisz lub zdecydujesz zignorować.

Ale ofc to super że w ogóle rozszerzamy hierarchię wyjątków, widać że wszystko jest bardzo przemyślane w tym PR.

IMO


<img width="837" alt="image" src="https://user-images.githubusercontent.com/52869032/163693175-0bf57d94-87bc-4ce7-ade9-73ae0933c10d.png">

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/service/PatientService.java
> -    public PatientService(PatientRepository patientRepository, PasswordEncoder passwordEncoder) {
Należy użyć `@AllArgsConstructor. Piszemy w Javie, więc tym bardziej starajmy się **agresywnie wycinać boilerplate** dla dobra wszystkich. Naprawdę uważam, że to akurat powinno być naprawione (inne rzeczy to bardziej sugestie) @adambiel22 .

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/service/PatientService.java
> +        if (!vaccine.isPresent()) {
Warto zmienić na `vaccine.isEmpty()` (bez niepotrzebnego przeczenia przez `!`). W tym szczególnym przypadku można też skorzystać z `vaccine.ifPresentOrElse(null, () -> {throw new ...})`, ale taki wybór byłby raczej ideologiczny.

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/service/PatientService.java
> +        if (!vaccinationSlot.isPresent()) {
jak wyżej

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/service/PatientService.java
> +        vaccinationRepository.save(new VaccinationEntity(
Podoba mi się tutaj bardzo ta technika "guardów" i wykorzystanie wyjątków (chociaż źle zdefiniowanych). Widać jak powoli dochodzimy do tego co się ma stać i jak dużo założeń musi być spełnionych przed otrzymaniem nagrody jaką jest wykonanie linijek 76-80. **Pytanie czy niektórych z tych założeń nie da się wyeliminować w jakiś lepszy sposób.**

IMO

2022-04-16 23:11 UTC, filipspych commented on src/main/java/com/example/SOPSbackend/service/PatientService.java
> +        vaccinationRepository.save(new VaccinationEntity(
Wygląda na to, że się nie da (to naprawde bardzo przemyślany kod 😍).

2022-04-18 17:25 UTC, merged